### ISSUE TITLE
WireGuard VPN Port Forwarding Broken with Custom/Torguard

### ISSUE THREAD

**Issue by visualblind** [qdm12/gluetun-wiki#148]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md

### What's incorrect?

I would first like to say, I think it's a mistake to attempt to hardcode every VPN providers server list according to provider and protocol. This is why the VPN providers provide multi-homed DNS records.

As far as I can tell there is no way to get port forwarding working with WireGuard using the "Custom" provider for my provider, Torguard. If this is incorrect please let me know.

I got WireGuard working, except for port forwarding with the following config:

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=37.120.147.130
      - WIREGUARD_ENDPOINT_PORT=1443
      - WIREGUARD_PUBLIC_KEY=<redacted>
      - WIREGUARD_PRIVATE_KEY=<redacted>
      - WIREGUARD_ADDRESSES="10.13.128.109/24"
      - WIREGUARD_MTU=1390
      - WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL=25s

    ports:
      - 9091:9091/tcp
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Los_Angeles
      - PUID=921
      - PGID=3000
    volumes:
      - /mnt/pool0/iocage/jails/transmission/root/usr/local/etc/transmission-new/config:/config
    restart: unless-stopped
```

However once this is added: 

```
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_LISTENING_PORT=47130
      - VPN_PORT_FORWARDING_PROVIDER=torguard
      - SERVER_HOSTNAMES=us-la.torguard.org
```

I get the error:

> ERROR VPN settings: provider settings: port forwarding: port forwarding cannot be enabled: value is not one of the possible choices: torguard must be one of perfect privacy, private internet access, privatevpn or protonvpn.

I'm not sure how other provider do it, but with Torguard you basically pin port forwarding against a single IP address, not a "server hostname". That's just one of the reasons I think trying to maintain a duplicate hard coded server list is a bad idea. I really can't think of any benefit of having a hard coded list that you have to continuously update.
