### ISSUE TITLE
Your credentials might be wrong with protonVPN

### ISSUE THREAD

**Issue by morhodesly** [qdm12/gluetun-wiki#38]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md

### What's misleading?

I follow the wiki on how to implement the protonVPN into gluetun. After the container starts running it gets me the error message `ERROR [openvpn] AUTH: Received control message: AUTH_FAILED`. can someone help me? I attach below my docker-compose.yml

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER='username_from_protonvpn_account'
      - OPENVPN_PASSWORD='password_from_protonvpn_account'
      - SERVER_COUNTRIES=Netherlands
```
