### ISSUE TITLE
HTTP Proxy through SwitchyOmega shows local WAN IP

### ISSUE THREAD

**Issue by truthsword** [qdm12/gluetun-wiki#47]
Something simple, so vexing... Here's my docker-compose:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
    environment:
      - HTTPPROXY=on
```
(truncated airvpn setup)

My host is 192.168.1.42, so in SwitchyOmega Proxy I used 192.168.1.42:8888 for HTTP setting (default) and set HTTPS to use default.

When selecting the proxy profile and loading whatismyip on my browser, I get my local WAN address. I've tried changing the browser proxy settings as well, and using the docker container IP (172.24.05) without any change. I'm sure this is user error, but I'm stuck. Thanks for any assistance.
