### ISSUE TITLE
Feedback: IPv6

### ISSUE THREAD

**Issue by Vexz00** [qdm12/gluetun-wiki#70]
I'm referring to this:
`⚠️ IPv6 is an experimental Docker feature, no thorough test was done to ensure there is no IP/DNS leak with Gluetun configured with IPv6. Feel free to create an issue or pull request if you have some testing done and can confirm.`
[Wiki-source](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/ipv6.md)

**tl;dr**: IPv6 with Gluetun works fine and there's no DNS leak from what I can tell.

**Longer version:**
- I live in Germany.
- I have dual stack (IPv4 + IPv6). → In Germany I get a GUA starting with `2003:...`
- I use Mullvad VPN.
- I usually let my DNS leak intentionally because I rather use NextDNS for some additional filtering instead of the privacy aspect you gain from routing your DNS through the VPN tunnel. But for this test I used Gluetun's Unbound.

Here's my docker compose script that I used:
```yml
version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun:v3.38
    container_name: Gluetun_VPN
    network_mode: "bridge"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<MY PRIVATE KEY>
      - WIREGUARD_ADDRESSES=10.66.243.129/32,fc00:bbbb:bbbb:bb01::3:f380/128
      - SERVER_CITIES=Zurich
    ports:
      - 1080:1080
    restart: always

  socks5:
    image: serjs/go-socks5-proxy:latest
    container_name: Go-Socks5-Proxy
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: always
``` 

The proxy settings in Firefox were set accordingly to connect to the docker container.

**Results:**
- [Screenshot of my IP-addresses](https://screenshot.hostux.net/u/ESqZfR.png)
- [Screenshot of a DNS leak test](https://screenshot.hostux.net/u/HjxOgK.png)
