### ISSUE TITLE
Not connecting to servers in the specified region

### ISSUE THREAD

**Issue by jpcapone** [qdm12/gluetun-wiki#86]
```
`services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=xxxxxx
      - OPENVPN_PASSWORD=xxxxxxx
      - SERVER_REGIONS=Bahamas
      - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=xxxxxxxx
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8180:8180
      - 8000:8000`

```
As you can see in my docker compose file I have specified the bahamas however in the logs I see
![image](https://github.com/qdm12/gluetun-wiki/assets/47680328/3d3f5fd8-628c-48da-aa3f-f8a8c6a32010)
and
![image](https://github.com/qdm12/gluetun-wiki/assets/47680328/068b10f8-82dd-4ad5-a9cd-9895cf054150)

What am I missing?
