### ISSUE TITLE
Update docker-compose.yml to access /dev/net/tun

### ISSUE THREAD

**Issue by Chillsmeit** [qdm12/gluetun-wiki#88]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers

### What's missing?

Update all the VPNs docker-compose.yml with the tun device permission.
The default docker-compose.yml files in this wiki are outdated and won't work due to missing permissions.
For example for ProtonVPN would be like so:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=abc
      - OPENVPN_PASSWORD=abc
      - SERVER_COUNTRIES=Netherlands
```
